/**
 * grunt-qunit-blanket-lcov
 * https://github.com/mistic100/grunt-qunit-blanket-lcov
 *
 * Copyright (c) 2015 Damien "Mistic" Sorel
 * Licensed under the MIT license.
 */

"use strict";

var path = require('path');

module.exports = function(grunt) {

    grunt.registerMultiTask('qunit_blanket_lcov', 'Save LCOV reports generated by Blanket for Grunt QUnit.', function() {
        var options = this.options({
            inject_reporter: true,
            dest: null
        });

        if (!options.dest) {
            grunt.log.error('No destination file provided to qunit-blanket-lcov');
            return;
        }

        if (options.inject_reporter) {
            grunt.config.merge({
                qunit: {
                    options: {
                        inject: [
                            path.join(__dirname, '../../grunt-contrib-qunit/phantomjs/bridge.js'),
                            path.join(__dirname, '../reporter.js')
                        ]
                    }
                }
            });
        }

        var files = {};
        this.files.forEach(function(file) {
            files[file.src[0]] = true;
        });

        grunt.event.on('qunit.report', function(data) {
            var str = '';

            for (var file in data) {
                var relFile = path.relative(process.cwd(), file.replace('file:///', '')).split(path.sep).join('/');

                if (files[relFile]) {
                    str+= 'SF:' + relFile + '\n';

                    data[file].forEach(function(val, line) {
                        if (val !== undefined && val !== null) {
                            str+= 'DA:' + line + ',' + val + '\n';
                        }
                    });

                    str+= 'end_of_record\n';
                }
            }

            grunt.file.write(options.dest, str);

            grunt.log.ok('LCOV file created');
        });
    });

};